import { RawListing } from './types'

export const MOCK_RAW_LISTINGS: RawListing[] = [
  {
    id: 'mock-1',
    title: '4BR Villa — Palm Jumeirah',
    location: 'Palm Jumeirah, Dubai',
    neighborhood: 'Palm Jumeirah',
    source: 'propertyfinder.ae',
    url: 'https://www.propertyfinder.ae/en/search',
    price: 6500000,
    currency: 'USD',
    beds: 4,
    baths: 5,
    sqft: 5200,
    propertyType: 'villa',
  },
  {
    id: 'mock-2',
    title: '3BR Penthouse — Downtown Dubai',
    location: 'Downtown Dubai, Dubai',
    neighborhood: 'Downtown Dubai',
    source: 'sothebysrealty.ae',
    url: 'https://www.sothebysrealty.ae',
    price: 9800000,
    currency: 'USD',
    beds: 3,
    baths: 4,
    sqft: 4100,
    propertyType: 'penthouse',
  },
  {
    id: 'mock-3',
    title: '5BR Signature Villa — Palm Jumeirah',
    location: 'Palm Jumeirah, Dubai',
    neighborhood: 'Palm Jumeirah',
    source: 'propertyfinder.ae',
    url: 'https://www.propertyfinder.ae/en/search',
    price: 15000000,
    currency: 'USD',
    beds: 5,
    baths: 6,
    sqft: 8800,
    propertyType: 'villa',
  },
  {
    id: 'mock-4',
    title: '4BR Villa — Palm Jumeirah Frond',
    location: 'Palm Jumeirah, Dubai',
    neighborhood: 'Palm Jumeirah',
    source: 'propertyfinder.ae',
    url: 'https://www.propertyfinder.ae/en/search',
    price: 7200000,
    currency: 'USD',
    beds: 4,
    baths: 5,
    sqft: 5600,
    propertyType: 'villa',
  },
  {
    id: 'mock-5',
    title: '2BR Apartment — Dubai Marina',
    location: 'Dubai Marina, Dubai',
    neighborhood: 'Dubai Marina',
    source: 'propertyfinder.ae',
    url: 'https://www.propertyfinder.ae/en/search',
    price: 1800000,
    currency: 'USD',
    beds: 2,
    baths: 2,
    sqft: 1400,
    propertyType: 'apartment',
  },
  {
    id: 'mock-6',
    title: '3BR Apartment — Dubai Marina',
    location: 'Dubai Marina, Dubai',
    neighborhood: 'Dubai Marina',
    source: 'sothebysrealty.ae',
    url: 'https://www.sothebysrealty.ae',
    price: 2600000,
    currency: 'USD',
    beds: 3,
    baths: 3,
    sqft: 1900,
    propertyType: 'apartment',
  },
  {
    id: 'mock-7',
    title: '1BR Studio — Downtown Dubai',
    location: 'Downtown Dubai, Dubai',
    neighborhood: 'Downtown Dubai',
    source: 'propertyfinder.ae',
    url: 'https://www.propertyfinder.ae/en/search',
    price: 950000,
    currency: 'USD',
    beds: 1,
    baths: 1,
    sqft: 750,
    propertyType: 'apartment',
  },
  {
    id: 'mock-8',
    title: '4BR Townhouse — Arabian Ranches',
    location: 'Arabian Ranches, Dubai',
    neighborhood: 'Arabian Ranches',
    source: 'propertyfinder.ae',
    url: 'https://www.propertyfinder.ae/en/search',
    price: 3100000,
    currency: 'USD',
    beds: 4,
    baths: 3,
    sqft: 3200,
    propertyType: 'townhouse',
  },
  {
    id: 'mock-9',
    title: '6BR Mega Villa — Palm Jumeirah',
    location: 'Palm Jumeirah, Dubai',
    neighborhood: 'Palm Jumeirah',
    source: 'sothebysrealty.ae',
    url: 'https://www.sothebysrealty.ae',
    price: 25000000,
    currency: 'USD',
    beds: 6,
    baths: 8,
    sqft: 12000,
    propertyType: 'villa',
  },
  {
    id: 'mock-10',
    title: '2BR Penthouse — Downtown Dubai',
    location: 'Downtown Dubai, Dubai',
    neighborhood: 'Downtown Dubai',
    source: 'sothebysrealty.ae',
    url: 'https://www.sothebysrealty.ae',
    price: 4200000,
    currency: 'USD',
    beds: 2,
    baths: 3,
    sqft: 2100,
    propertyType: 'penthouse',
  },
]
